name: Manual Nightly release

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Specify the branch you want
          ref: development
          fetch-depth: 0

      - name: Force sync with latest development
        run: |
          git fetch origin development
          git checkout development
          git reset --hard origin/development

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Shaded JAR
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          mvn clean package -Dmicrobot.commit.sha=$COMMIT_SHA

      - name: Read microbot.version from POM
        id: version
        run: |
          V=$(mvn -q -f runelite-client/pom.xml help:evaluate \
                -Dexpression=microbot.version -DforceStdout)
          # fallback to project.version if the property isn't defined
          if [ -z "$V" ]; then
            V=$(mvn -q -f runelite-client/pom.xml help:evaluate \
                  -Dexpression=project.version -DforceStdout)
          fi
          echo "version=$V" >> "$GITHUB_OUTPUT"
          echo "Using version: $V"

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: false
          title: "Nightly Build"
          files: |
            runelite-client/target/microbot-*.jar