name: Manual Nightly Build

on:
  workflow_dispatch:

env:
  version: ${microbot.version}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Specify the branch you want
          ref: development
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Shaded JAR
        run: mvn clean package

      - name: Extract microbot & ruinelite versions from pom.xml
        id: version
        run: |
          microbot=$(grep -oPm1 "(?<=<microbot.version>)[^<]+" runelite-client/pom.xml)
          ruinelite=$(grep -oPm1 "(?<=<ruinelite.version>)[^<]+" runelite-client/pom.xml)
          combined="${microbot}-${ruinelite}"
          echo "version=$combined" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-build"
          prerelease: false
          title: "Nightly Build"
          files: |
            runelite-client/target/microbot-${{ steps.version.outputs.version }}.jar
