name: Nightly release

on:
  schedule:
    - cron: "0 0 * * *"

env:
  version: "1.9.7"

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Specify the branch you want
          ref: development
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Shaded JAR
        run: mvn clean package

      - name: Extract Ruinelite version from pom.xml
        id: version
        run: |
          version=$(grep -oPm1 "(?<=<ruinelite.version>)[^<]+" runelite-client/pom.xml)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Extract combined version from pom.xml
        id: combined_version
        run: |
          combined=$(grep -oPm1 '(?<=<combined.version>)[^<]+' runelite-client/pom.xml)
          echo "combined=$combined" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: false
          title: "Nightly Build"
          files: |
            runelite-client/target/microbot-${{ steps.combined_version.outputs.combined }}.jar

