name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Shaded JAR
        run: mvn clean package

      - name: Extract Microbot version from pom.xml
        id: version
        run: |
          version=$(grep -oPm1 "(?<=<microbot.version>)[^<]+" runelite-client/pom.xml)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ steps.version.outputs.version }}"
          name: "Release ${{ steps.version.outputs.version }}"
          generate_release_notes: true
          files: |
            runelite-client/target/microbot-${{ steps.version.outputs.version }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}