name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Shaded JAR
        run: mvn clean package

      - name: Extract Microbot version from pom.xml
        id: version
        run: |
          version=$(grep -oPm1 "(?<=<microbot.version>)[^<]+" runelite-client/pom.xml)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.version.outputs.version }}"
          prerelease: false
          title: "Release ${{ steps.version.outputs.version }}"
          files: |
            runelite-client/target/microbot-${{ steps.version.outputs.version }}.jar
